---
- hosts: all
  vars:
    user: pi
    user_home: '/home/{{ user }}'
    deploy_dir: '{{ user_home }}/traffic_light'
    miniconda_version: Miniconda3-latest-Linux-armv7l.sh
    miniconda_install_dir: '{{ user_home }}/miniconda'
    miniconda_env: traffic_light
  become: yes
  gather_facts: true

  tasks:
  - name: Update repo cache
    apt:
      autoclean: yes
      autoremove: yes
      update_cache: yes

  - name: Install packages
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - git
      - nginx

  - name: Download miniconda installer
    get_url:
      url: "https://repo.continuum.io/miniconda/{{ miniconda_version }}"
      dest: "/tmp/{{ miniconda_version }}"
      mode: 0555

  - name: Install miniconda
    command: "/tmp/{{ miniconda_version }} -b -p {{ miniconda_install_dir }}"
    args:
      creates: "{{ miniconda_install_dir }}"
    become: no

  - name: Deploy project
    git:
      repo: https://github.com/antvick/traffic_light.git
      dest: "{{ deploy_dir }}"
      version: feature/deploy
      force: yes
    become: no

  - name: Remove API environment
    # can't use `./run restore` because `--prune` arg isn't available on ARM miniconda binary
    command: "{{ miniconda_install_dir }}/bin/conda env remove -n {{ miniconda_env }} --yes"
    args:
      chdir: "{{ deploy_dir }}/src/api"
    become: no

  - name: Restore API environment
    command: "{{ miniconda_install_dir }}/bin/conda env update -n {{ miniconda_env }} -f prod_environment.yml -q QUIET"
    args:
      chdir: "{{ deploy_dir }}/src/api"
    become: no

