#!/bin/bash
set -eou pipefail
ENV="traffic_light"
THISDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
# shellcheck disable=1090
source "$THISDIR/../run_funcs"

function cmd_serve(){
    (
        cd "$THISDIR"
        source activate "$ENV"
        gunicorn app:app --bind 0.0.0.0:8000 --workers 1
    )
}

function cmd_dev(){
    (
        cd "$THISDIR"
        source activate "$ENV"
        python -m app
    )
}

function cmd_default(){
    run_cmd "preflight"
    run_cmd "restore"
    run_cmd "dev"
}

function cmd_restore(){
    conda env update -n "$ENV" --quiet --prune -f "$THISDIR/environment.yml"
}

function cmd_environment(){
    source activate "$ENV"
}

function cmd_preflight(){
    { command -v conda > /dev/null && echo "OK"; } || { echo 'Missing conda, you need to install it' && exit 9; }
}

cmd="${1:-default}"
shift || true
case "$cmd" in
  default|restore|dev|serve)
    run_cmd "$cmd" "$@"
    ;;
  *)
    echo "Usage: $0 {default|restore|dev}"
    ;;
esac